package net.wiibleyde.themynthos.entity.client;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class MynthosAnimations {


    public static final AnimationDefinition ANIM_MYNTHOS_WALK = AnimationDefinition.Builder.withLength(1.78439f).looping()
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.2974f, KeyframeAnimations.degreeVec(0f, 0f, 1.67f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4461f, KeyframeAnimations.degreeVec(0f, 0f, 2.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5948f, KeyframeAnimations.degreeVec(0f, -1.67f, 1.67f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.74349f, KeyframeAnimations.degreeVec(0f, -3.33f, 0.83f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.89219f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.04089f, KeyframeAnimations.degreeVec(0f, -3.33f, -0.83f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.18959f, KeyframeAnimations.degreeVec(0f, -1.67f, -1.67f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.33829f, KeyframeAnimations.degreeVec(0f, 0f, -2.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.48699f, KeyframeAnimations.degreeVec(0f, 0f, -1.67f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.78439f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("leg0",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.1487f, KeyframeAnimations.degreeVec(0.22f, -0.22f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.2974f, KeyframeAnimations.degreeVec(-0.11f, 2.61f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4461f, KeyframeAnimations.degreeVec(-2.5f, 2.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5948f, KeyframeAnimations.degreeVec(-2.72f, 2.72f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.74349f, KeyframeAnimations.degreeVec(-2.39f, -0.11f, 0.1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.89219f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("leg1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0.89219f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.04089f, KeyframeAnimations.degreeVec(0.22f, -0.22f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.18959f, KeyframeAnimations.degreeVec(-0.11f, 0.11f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.33829f, KeyframeAnimations.degreeVec(-2.5f, -2.5f, 0.22f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.48699f, KeyframeAnimations.degreeVec(-2.44f, -2.56f, 0.21f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.63569f, KeyframeAnimations.degreeVec(-0.06f, 0.06f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.78439f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("leg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5948f, KeyframeAnimations.degreeVec(0f, 0.25f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.89219f, KeyframeAnimations.degreeVec(0f, -0.11f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.04089f, KeyframeAnimations.degreeVec(0f, -0.6f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.18959f, KeyframeAnimations.degreeVec(0f, -1.38f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.33829f, KeyframeAnimations.degreeVec(0f, -2.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.48699f, KeyframeAnimations.degreeVec(0f, -2.72f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.63569f, KeyframeAnimations.degreeVec(0f, -2.39f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.78439f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("leg3",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.1487f, KeyframeAnimations.degreeVec(0f, -0.45f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.2974f, KeyframeAnimations.degreeVec(0f, 0.22f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4461f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.74349f, KeyframeAnimations.degreeVec(0f, 4.78f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.89219f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM))).build();
    public static final AnimationDefinition ANIM_MYNTHOS_IDLE = AnimationDefinition.Builder.withLength(4.5f).looping()
            .addAnimation("leg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.11111f, KeyframeAnimations.degreeVec(0.21f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.22222f, KeyframeAnimations.degreeVec(0.78f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.33333f, KeyframeAnimations.degreeVec(1.57f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(2.97f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.77778f, KeyframeAnimations.degreeVec(4.87f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.88889f, KeyframeAnimations.degreeVec(5.16f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.11111f, KeyframeAnimations.degreeVec(4.39f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.22222f, KeyframeAnimations.degreeVec(3.34f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.33333f, KeyframeAnimations.degreeVec(1.98f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.44444f, KeyframeAnimations.degreeVec(0.39f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.55556f, KeyframeAnimations.degreeVec(-1.29f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.72222f, KeyframeAnimations.degreeVec(-3.78f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(-6.87f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.11111f, KeyframeAnimations.degreeVec(-7.43f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.22222f, KeyframeAnimations.degreeVec(-7.43f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.33333f, KeyframeAnimations.degreeVec(-6.87f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.44444f, KeyframeAnimations.degreeVec(-5.87f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.55556f, KeyframeAnimations.degreeVec(-4.54f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.66667f, KeyframeAnimations.degreeVec(-2.97f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.77778f, KeyframeAnimations.degreeVec(-1.29f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.94444f, KeyframeAnimations.degreeVec(1.2f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.22222f, KeyframeAnimations.degreeVec(4.39f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.33333f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.44444f, KeyframeAnimations.degreeVec(5.16f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.55556f, KeyframeAnimations.degreeVec(4.99f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.66667f, KeyframeAnimations.degreeVec(4.56f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.83333f, KeyframeAnimations.degreeVec(3.56f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4f, KeyframeAnimations.degreeVec(2.36f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.33333f, KeyframeAnimations.degreeVec(0.34f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.44444f, KeyframeAnimations.degreeVec(0.04f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("leg3",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.11111f, KeyframeAnimations.degreeVec(-0.2f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.22222f, KeyframeAnimations.degreeVec(-0.73f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.33333f, KeyframeAnimations.degreeVec(-1.48f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-2.81f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.77778f, KeyframeAnimations.degreeVec(-4.71f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.88889f, KeyframeAnimations.degreeVec(-5.05f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.11111f, KeyframeAnimations.degreeVec(-4.55f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.22222f, KeyframeAnimations.degreeVec(-3.74f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.33333f, KeyframeAnimations.degreeVec(-2.65f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.44444f, KeyframeAnimations.degreeVec(-1.39f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.61111f, KeyframeAnimations.degreeVec(0.65f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.83333f, KeyframeAnimations.degreeVec(3.16f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.05556f, KeyframeAnimations.degreeVec(4.77f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.16667f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.27778f, KeyframeAnimations.degreeVec(4.77f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.38889f, KeyframeAnimations.degreeVec(4.12f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(3.16f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.61111f, KeyframeAnimations.degreeVec(1.98f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.72222f, KeyframeAnimations.degreeVec(0.65f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.83333f, KeyframeAnimations.degreeVec(-0.71f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.05556f, KeyframeAnimations.degreeVec(-3.22f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.27778f, KeyframeAnimations.degreeVec(-4.83f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.38889f, KeyframeAnimations.degreeVec(-5.08f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.5f, KeyframeAnimations.degreeVec(-4.99f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.61111f, KeyframeAnimations.degreeVec(-4.63f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.77778f, KeyframeAnimations.degreeVec(-3.74f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.94444f, KeyframeAnimations.degreeVec(-2.62f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.16667f, KeyframeAnimations.degreeVec(-1.14f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.38889f, KeyframeAnimations.degreeVec(-0.15f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM))).build();
    public static final AnimationDefinition ANIM_MYNTHOS_SEAT = AnimationDefinition.Builder.withLength(4f)
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.posVec(0f, -0.14f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.41667f, KeyframeAnimations.posVec(0f, -0.24f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.625f, KeyframeAnimations.posVec(0f, -0.38f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.79167f, KeyframeAnimations.posVec(0f, -0.52f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.95833f, KeyframeAnimations.posVec(0f, -0.69f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.08333f, KeyframeAnimations.posVec(0f, -0.85f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.20833f, KeyframeAnimations.posVec(0f, -1.03f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.29167f, KeyframeAnimations.posVec(0f, -1.17f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.41667f, KeyframeAnimations.posVec(0f, -1.41f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.54167f, KeyframeAnimations.posVec(0f, -1.68f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.66667f, KeyframeAnimations.posVec(0f, -2f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.75f, KeyframeAnimations.posVec(0f, -2.43f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.79167f, KeyframeAnimations.posVec(0f, -2.68f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.875f, KeyframeAnimations.posVec(0f, -3.25f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.95833f, KeyframeAnimations.posVec(0f, -3.89f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.04167f, KeyframeAnimations.posVec(0f, -4.57f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.125f, KeyframeAnimations.posVec(0f, -5.27f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.20833f, KeyframeAnimations.posVec(0f, -5.98f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.29167f, KeyframeAnimations.posVec(0f, -6.67f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.41667f, KeyframeAnimations.posVec(0f, -7.62f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.66667f, KeyframeAnimations.posVec(0f, -9f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.08333f, KeyframeAnimations.degreeVec(0.91f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.16667f, KeyframeAnimations.degreeVec(2.07f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(3.44f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.33333f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.41667f, KeyframeAnimations.degreeVec(6.71f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(8.55f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.58333f, KeyframeAnimations.degreeVec(10.49f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.66667f, KeyframeAnimations.degreeVec(12.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.70833f, KeyframeAnimations.degreeVec(13.23f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.79167f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.875f, KeyframeAnimations.degreeVec(17.08f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.95833f, KeyframeAnimations.degreeVec(19.37f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.04167f, KeyframeAnimations.degreeVec(21.76f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.125f, KeyframeAnimations.degreeVec(24.15f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.25f, KeyframeAnimations.degreeVec(27.51f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.45833f, KeyframeAnimations.degreeVec(31.63f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.54167f, KeyframeAnimations.degreeVec(32.46f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.58333f, KeyframeAnimations.degreeVec(32.65f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.66667f, KeyframeAnimations.degreeVec(32.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.70833f, KeyframeAnimations.degreeVec(32.12f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.75f, KeyframeAnimations.degreeVec(31.53f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.79167f, KeyframeAnimations.degreeVec(30.73f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.83333f, KeyframeAnimations.degreeVec(29.75f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.91667f, KeyframeAnimations.degreeVec(27.3f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(24.35f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.08333f, KeyframeAnimations.degreeVec(21.03f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.16667f, KeyframeAnimations.degreeVec(17.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.25f, KeyframeAnimations.degreeVec(13.9f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.33333f, KeyframeAnimations.degreeVec(10.37f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.41667f, KeyframeAnimations.degreeVec(7.07f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.625f, KeyframeAnimations.degreeVec(0.78f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.66667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("leg0",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.16667f, KeyframeAnimations.posVec(0f, -0.18f, -0.11f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.33333f, KeyframeAnimations.posVec(0f, -0.42f, -0.25f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.41667f, KeyframeAnimations.posVec(0f, -0.55f, -0.33f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.58333f, KeyframeAnimations.posVec(0f, -0.85f, -0.51f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.70833f, KeyframeAnimations.posVec(0f, -1.1f, -0.66f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.79167f, KeyframeAnimations.posVec(0f, -1.27f, -0.76f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.91667f, KeyframeAnimations.posVec(0f, -1.54f, -0.93f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.04167f, KeyframeAnimations.posVec(0f, -1.82f, -1.09f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.125f, KeyframeAnimations.posVec(0f, -2.01f, -1.21f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.25f, KeyframeAnimations.posVec(0f, -2.3f, -1.38f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.375f, KeyframeAnimations.posVec(0f, -2.6f, -1.56f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.45833f, KeyframeAnimations.posVec(0f, -2.79f, -1.68f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.58333f, KeyframeAnimations.posVec(0f, -3.08f, -1.85f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.66667f, KeyframeAnimations.posVec(0f, -3.27f, -1.96f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.79167f, KeyframeAnimations.posVec(0f, -3.55f, -2.13f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.91667f, KeyframeAnimations.posVec(0f, -3.81f, -2.29f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.posVec(0f, -3.98f, -2.39f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.125f, KeyframeAnimations.posVec(0f, -4.22f, -2.53f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.29167f, KeyframeAnimations.posVec(0f, -4.51f, -2.71f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.45833f, KeyframeAnimations.posVec(0f, -4.76f, -2.86f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.66667f, KeyframeAnimations.posVec(0f, -5f, -3f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("leg0",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.08333f, KeyframeAnimations.degreeVec(-0.91f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.16667f, KeyframeAnimations.degreeVec(-2.07f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(-3.44f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.33333f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.41667f, KeyframeAnimations.degreeVec(-6.71f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-8.55f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.58333f, KeyframeAnimations.degreeVec(-10.49f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.66667f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.79167f, KeyframeAnimations.degreeVec(-14.38f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.91667f, KeyframeAnimations.degreeVec(-16.09f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.04167f, KeyframeAnimations.degreeVec(-17.8f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.125f, KeyframeAnimations.degreeVec(-19.03f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.20833f, KeyframeAnimations.degreeVec(-20.39f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.29167f, KeyframeAnimations.degreeVec(-21.92f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.375f, KeyframeAnimations.degreeVec(-23.7f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.45833f, KeyframeAnimations.degreeVec(-25.76f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.54167f, KeyframeAnimations.degreeVec(-28.15f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.625f, KeyframeAnimations.degreeVec(-30.94f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.66667f, KeyframeAnimations.degreeVec(-32.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.70833f, KeyframeAnimations.degreeVec(-34.23f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.75f, KeyframeAnimations.degreeVec(-36.16f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.83333f, KeyframeAnimations.degreeVec(-40.58f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.91667f, KeyframeAnimations.degreeVec(-45.59f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(-51.02f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.08333f, KeyframeAnimations.degreeVec(-56.71f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.16667f, KeyframeAnimations.degreeVec(-62.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.25f, KeyframeAnimations.degreeVec(-68.22f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.33333f, KeyframeAnimations.degreeVec(-73.7f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.41667f, KeyframeAnimations.degreeVec(-78.79f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.66667f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("leg1",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.16667f, KeyframeAnimations.posVec(0f, -0.18f, -0.11f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.33333f, KeyframeAnimations.posVec(0f, -0.42f, -0.25f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.41667f, KeyframeAnimations.posVec(0f, -0.55f, -0.33f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.58333f, KeyframeAnimations.posVec(0f, -0.85f, -0.51f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.70833f, KeyframeAnimations.posVec(0f, -1.1f, -0.66f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.79167f, KeyframeAnimations.posVec(0f, -1.27f, -0.76f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.91667f, KeyframeAnimations.posVec(0f, -1.54f, -0.93f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.04167f, KeyframeAnimations.posVec(0f, -1.82f, -1.09f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.125f, KeyframeAnimations.posVec(0f, -2.01f, -1.21f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.25f, KeyframeAnimations.posVec(0f, -2.3f, -1.38f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.375f, KeyframeAnimations.posVec(0f, -2.6f, -1.56f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.45833f, KeyframeAnimations.posVec(0f, -2.79f, -1.68f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.58333f, KeyframeAnimations.posVec(0f, -3.08f, -1.85f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.66667f, KeyframeAnimations.posVec(0f, -3.27f, -1.96f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.79167f, KeyframeAnimations.posVec(0f, -3.55f, -2.13f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.91667f, KeyframeAnimations.posVec(0f, -3.81f, -2.29f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.posVec(0f, -3.98f, -2.39f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.125f, KeyframeAnimations.posVec(0f, -4.22f, -2.53f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.29167f, KeyframeAnimations.posVec(0f, -4.51f, -2.71f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.45833f, KeyframeAnimations.posVec(0f, -4.76f, -2.86f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.66667f, KeyframeAnimations.posVec(0f, -5f, -3f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("leg1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.08333f, KeyframeAnimations.degreeVec(-0.91f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.16667f, KeyframeAnimations.degreeVec(-2.07f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(-3.44f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.33333f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.41667f, KeyframeAnimations.degreeVec(-6.71f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-8.55f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.58333f, KeyframeAnimations.degreeVec(-10.49f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.66667f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.79167f, KeyframeAnimations.degreeVec(-14.38f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.91667f, KeyframeAnimations.degreeVec(-16.09f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.04167f, KeyframeAnimations.degreeVec(-17.8f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.125f, KeyframeAnimations.degreeVec(-19.03f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.20833f, KeyframeAnimations.degreeVec(-20.39f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.29167f, KeyframeAnimations.degreeVec(-21.92f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.375f, KeyframeAnimations.degreeVec(-23.7f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.45833f, KeyframeAnimations.degreeVec(-25.76f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.54167f, KeyframeAnimations.degreeVec(-28.15f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.625f, KeyframeAnimations.degreeVec(-30.94f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.66667f, KeyframeAnimations.degreeVec(-32.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.70833f, KeyframeAnimations.degreeVec(-34.23f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.75f, KeyframeAnimations.degreeVec(-36.16f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.83333f, KeyframeAnimations.degreeVec(-40.58f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.91667f, KeyframeAnimations.degreeVec(-45.59f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(-51.02f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.08333f, KeyframeAnimations.degreeVec(-56.71f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.16667f, KeyframeAnimations.degreeVec(-62.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.25f, KeyframeAnimations.degreeVec(-68.22f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.33333f, KeyframeAnimations.degreeVec(-73.7f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.41667f, KeyframeAnimations.degreeVec(-78.79f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.66667f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("leg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.08333f, KeyframeAnimations.degreeVec(-1.14f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.16667f, KeyframeAnimations.degreeVec(-2.64f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(-4.42f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.33333f, KeyframeAnimations.degreeVec(-6.41f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.41667f, KeyframeAnimations.degreeVec(-8.53f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-10.72f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.58333f, KeyframeAnimations.degreeVec(-12.9f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.66667f, KeyframeAnimations.degreeVec(-15f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.70833f, KeyframeAnimations.degreeVec(-15.69f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.79167f, KeyframeAnimations.degreeVec(-17.3f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.875f, KeyframeAnimations.degreeVec(-19.14f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.95833f, KeyframeAnimations.degreeVec(-21.13f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.04167f, KeyframeAnimations.degreeVec(-23.19f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.125f, KeyframeAnimations.degreeVec(-25.24f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.25f, KeyframeAnimations.degreeVec(-28.11f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.45833f, KeyframeAnimations.degreeVec(-31.71f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.54167f, KeyframeAnimations.degreeVec(-32.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.625f, KeyframeAnimations.degreeVec(-32.79f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.70833f, KeyframeAnimations.degreeVec(-32.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.75f, KeyframeAnimations.degreeVec(-32.05f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.79167f, KeyframeAnimations.degreeVec(-31.37f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.83333f, KeyframeAnimations.degreeVec(-30.49f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.875f, KeyframeAnimations.degreeVec(-29.41f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.95833f, KeyframeAnimations.degreeVec(-26.77f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.04167f, KeyframeAnimations.degreeVec(-23.61f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.125f, KeyframeAnimations.degreeVec(-20.11f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.20833f, KeyframeAnimations.degreeVec(-16.41f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.29167f, KeyframeAnimations.degreeVec(-12.69f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.375f, KeyframeAnimations.degreeVec(-9.11f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(-4.35f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.66667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("leg3",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.08333f, KeyframeAnimations.degreeVec(-1.16f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.16667f, KeyframeAnimations.degreeVec(-2.7f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(-4.53f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.33333f, KeyframeAnimations.degreeVec(-6.56f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.41667f, KeyframeAnimations.degreeVec(-8.72f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-10.9f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.58333f, KeyframeAnimations.degreeVec(-13.02f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.66667f, KeyframeAnimations.degreeVec(-15f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(-16.33f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.83333f, KeyframeAnimations.degreeVec(-17.88f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.91667f, KeyframeAnimations.degreeVec(-19.58f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-21.37f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.08333f, KeyframeAnimations.degreeVec(-23.16f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.20833f, KeyframeAnimations.degreeVec(-25.72f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.45833f, KeyframeAnimations.degreeVec(-29.52f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.54167f, KeyframeAnimations.degreeVec(-30.14f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.625f, KeyframeAnimations.degreeVec(-30.32f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.70833f, KeyframeAnimations.degreeVec(-30f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.75f, KeyframeAnimations.degreeVec(-29.56f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.79167f, KeyframeAnimations.degreeVec(-28.92f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.875f, KeyframeAnimations.degreeVec(-27.08f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.95833f, KeyframeAnimations.degreeVec(-24.63f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.04167f, KeyframeAnimations.degreeVec(-21.71f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.125f, KeyframeAnimations.degreeVec(-18.48f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.20833f, KeyframeAnimations.degreeVec(-15.08f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.29167f, KeyframeAnimations.degreeVec(-11.66f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.375f, KeyframeAnimations.degreeVec(-8.37f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(-4f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.66667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM))).build();

}
